
build_on_debian:
  image: debian:stretch
  variables:
    ANDROID_HOME: /usr/lib/android-sdk
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - echo 'skipping sdkmanager, deps come from apt-get'
  script:
    - printf 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";\n'
        > /etc/apt/apt.conf.d/99no-install-recommends
    - printf 'APT::Acquire::Retries "20";\n'
        > /etc/apt/apt.conf.d/99acquire-retries
    - printf 'APT::Get::Assume-Yes "true";\n'
        > /etc/apt/apt.conf.d/99assumeyes
    - sed -i 's, main$, main contrib,' /etc/apt/sources.list
    - apt-get update
    - apt-get upgrade
    - apt-get install git wget
    - apt-get install --install-recommends
          android-sdk
          android-sdk-platform-23
          google-android-m2repository-installer
          libgradle-android-plugin-java
    - gradle assemble
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_${CI_JOB_NAME}"
    paths:
      - app/build/outputs/apk/*.apk
    expire_in: 1 week
    when: on_success
  after_script:
    - echo "Download debug artifacts from https://gitlab.com/${CI_PROJECT_PATH}/-/jobs"
